baseapp/urls.py
from django.urls import path, include
from django.conf.urls import url, include

from . import views

app_name = 'baseapp'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup-consumer/$', views.SignUpConsumerView.as_view(), name='sign-up-consumer'),
    url(r'^signup-business/$', views.SignUpBusinessView.as_view(), name='sign-up-business'),
    url(r'^business/dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^business/dashboard/location/$', views.DashboardLocation.as_view(), name='location'),
    url(r'^business/add-product/$', views.AddProductView.as_view(), name='add_product'),
    url(r'^business/chart-data/$', views.ChartDataView.as_view(), name='chart-data'),
    url(r'^business/products-list/$', views.ProductsListView.as_view(), name='products_list'),
    url(r'^consumer/feed/$', views.FeedView.as_view(), name='feed'),
    url(r'^consumer/feed/money/$', views.FeedAdvertisement.as_view(), name='advertisement'),
    url(r'^consumer/feed/points/$', views.FeedPoints.as_view(), name='points'),
    url(r'^consumer/feed/food-upload/$', views.FeedFoodUpload.as_view(), name='food-upload'),
    url(r'^consumer/feed/loc-range/$', views.LocationRangeView.as_view(), name='location-range'),
    url(r'^consumer/feed/community-pic/$', views.CommunityPicView.as_view(), name='community-pic'),
    url(r'^consumer/profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^consumer/feed/suggestions/', views.FoodRequest.as_view(), name='suggestions'),
    url(r'^consumer/feed/rate/', views.FoodRate.as_view(), name='rate'),
    url(r'^consumer/feed/pref-tags/', views.FoodPref.as_view(), name='pref-tags'),

    url(r'^populate', views.Populate.as_view()),
]

tindero/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('baseapp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baseapp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.BooleanField(max_length=20, default=True)

    def __str__(self):
        return self.user.username

    def getUserType(self):
        return self.user_type

class Customer(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    b_day = models.DateField( ("Date"), default=datetime.date.today, null = True)
    points = models.IntegerField(default = '0', null = True)
    loc_range = models.IntegerField(default = '3', null = True)
    pic = models.ImageField(upload_to='consumer_pic', default='consumer_pic/consumer.png', null = True)
    tag = models.TextField(default='', blank = True)

    def __str__(self):
        return self.user_profile.user.username

class Business(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to='business_pic', default='business_pic/business.png', null = True)
    company_name = models.CharField(max_length=40, default='DEFAULT VALUE')
    branch_name = models.CharField(max_length=40, default='DEFAULT VALUE')
    address = models.CharField(max_length=100 , default='DEFAULT VALUE')
    location = models.CharField(max_length=100 , default='DEFAULT VALUE')


    def __str__(self):
        return self.user_profile.user.username + self.company_name

class Food(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default='DEFAULT VALUE')
    pic = models.ImageField(upload_to='food_pic', default='food_pic/food.png', null=True)
    price = models.FloatField(default = '0')
    tag = models.TextField(default='', blank=True)
    desc = models.TextField(default='', blank=True)

    def __str__(self):
        return self.business.user_profile.user.username + "::" +self.name

class Ratings(models.Model):
    food_id = models.IntegerField()
    user_id = models.IntegerField()
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)


class Photo(models.Model):
    file = models.ImageField(upload_to='uploaded_pic')

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

class ConsumerPhoto(models.Model):
    file_file = models.ImageField(upload_to='consumer_pic')

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

class BusinessPhoto(models.Model):
    file = models.ImageField(upload_to='business_pic')

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

class FoodPhoto(models.Model):
    file = models.ImageField(upload_to='food_pic')

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'

class Advertisements(models.Model):
    name = models.CharField(max_length=20, default='DEFAULT VALUE')
    pic = models.ImageField(upload_to='Advertisements', default='', null=True)
    price = models.FloatField(default = '0')
    tag = models.TextField(default='', blank=True)
    desc = models.TextField(default='', blank=True)
    url = models.TextField(default='', blank=True)


class Rewards(models.Model):
    name = models.CharField(max_length=20, default='DEFAULT VALUE')
    pic = models.ImageField(upload_to='Rewards', default='', null=True)
    points = models.FloatField(default = '0')


class FoodForUpload(models.Model):
    consumer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    food_id = models.IntegerField()

class CommunityPic(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    url = models.TextField(default='', blank=True)

baseapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from django.core.files import File

from .models import UserProfile, Business, Customer, Food, FoodPhoto, BusinessPhoto, ConsumerPhoto, Photo, FoodForUpload, CommunityPic
from PIL import Image

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length = 100)

class RegisterForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'id':'username','class': 'input is-rounded', 'type':'text', 'placeholder': 'username', 'name':'username', 'v-model':'username'}))
    email=forms.EmailField(
        widget=forms.EmailInput(attrs={'id':'email','class': 'input is-rounded','type':'email', 'placeholder': 'dummy123@gmail.com', 'name':'email', 'v-model':'email'}), max_length=64, help_text='Enter a valid email address')
    password1=forms.CharField(
        widget=forms.PasswordInput(attrs={'id':'password1','class': 'input is-rounded','type':'password', 'placeholder': 'password'}))
    password2=forms.CharField(
        widget=forms.PasswordInput(attrs={'id':'password2','class': 'input is-rounded','type':'password', 'placeholder': 'confirm password'}))
    userType=forms.CharField(
        widget=forms.TextInput(attrs={'id':'user_type','class': 'input is-rounded', 'type':'text', 'placeholder': 'username', 'name':'username', 'v-model':'accountType', 'readonly':"readonly"}))


    class Meta:
        model = User
        fields = ("username","password1","password2", "email", "userType")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self):

        type_of_user = self.cleaned_data["userType"]
        user_type = True

        if (type_of_user == "business account"):
            user_type = False
        else:
            user_type = True

        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()

        userP = UserProfile(user = user, user_type = user_type)
        userP.save()

        return user

class BusinessForm(forms.Form):
    company_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input is-rounded', 'type':'text','placeholder':'company name'}))
    branch_name = forms.CharField(
        widget=forms.TextInput(attrs={'id':'branch_name','class': 'input is-rounded', 'type':'text','placeholder':'branch name'}))
    # branch_address = forms.CharField(
    #     widget=forms.TextInput(attrs={'class': 'input is-rounded', 'type':'text','placeholder':'branch location'}))

    def save(self):
        userP = UserProfile.objects.latest('user_id')

        business = Business(
            user_profile = userP,
            branch_name = self.cleaned_data["branch_name"],
            company_name = self.cleaned_data["company_name"]
        )

        business.save()

class ConsumerForm(forms.Form):

    def save(self):
        userP = UserProfile.objects.latest('user_id')
        consumer = Customer(user_profile = userP)
        consumer.save()

class FoodForm(forms.Form):
    food_name = forms.CharField(
        widget=forms.TextInput(attrs={
                                    'class':'input',
                                    'type':'text',
                                    'placeholder':'food name',
                                    'name':'foodname',
                                    'v-validate':'\'required\'',
                                    'v-model':'foodName'}))
    food_price = forms.FloatField(
        widget=forms.TextInput(attrs={
                                    'class':'input',
                                    'type':'text',
                                    'placeholder':'price',
                                    'name':'price',
                                    'v-validate':'\'required|decimal\'',
                                    'v-model':'price'}))

    food_description = forms.CharField(
        widget=forms.Textarea(attrs={
                                    'class':'textarea desc-text-area',
                                    'placeholder':'place yummy product description here',
                                    'rows':'8',
                                    'name':'description',
                                    'v-validate':'\'required|alpha_spaces|max:100\'',
                                    'v-model':'description'}))

    food_tags = forms.CharField(
        widget=forms.TextInput(attrs={
                                    'id':'foodtags',
                                    'class':'input',
                                    'type':'text',
                                    'placeholder':'put accurate tags to imporve discoverability',
                                    'name':'tags',
                                    'v-model':'tagTextField',
                                    'v-on:keydown.enter':'addTag'}))


    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(FoodForm, self).__init__(*args, **kwargs)

    def save(self):

        current_user = self.user
        user_profile = UserProfile.objects.get(user = current_user)
        #it would be better if we could save the User.id as a field in UserProfile
        print(Business.objects.get(user_profile = user_profile))
        current_business = Business.objects.get(user_profile = user_profile)
        food = Food(
            business = current_business,
            name = self.cleaned_data["food_name"],
            price = self.cleaned_data["food_price"],
            tag = self.cleaned_data["food_tags"],
            desc = self.cleaned_data["food_description"]
        )
        food.save()


class EditProfileForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input is-rounded', 'type':'text','placeholder':'name'}))
    bDay = forms.DateField(label='Birthday',
        widget=forms.SelectDateWidget(years=[y for y in range(1930,2050)]))

    def clean_name(self):
        return self.cleaned_data["first_name"]

    def clean_bday(self):
        return self.cleaned_data["bDay"]

class PhotoConsumerForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = ConsumerPhoto
        fields = ('file_file', 'x', 'y', 'width', 'height',)

    def save(self):
        photo = super(PhotoConsumerForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file_file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((128,128), Image.ANTIALIAS)
        resized_image.save(photo.file_file.path)

        return photo

class PhotoBusinessForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = BusinessPhoto
        fields = ('file', 'x', 'y', 'width', 'height',)

    def save(self):
        photo = super(PhotoBusinessForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((128,128), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

class PhotoFoodForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = FoodPhoto
        fields = ('file', 'x', 'y', 'width', 'height',)

    def save(self):
        photo = super(PhotoFoodForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((960,720), Image.ANTIALIAS)
        resized_image.save(photo.file.path)

        return photo

class PhotoUploadForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    object_id = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file','x', 'y', 'width', 'height')

    def save(self):
        photo = super(PhotoUploadForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')

baseapp/templates/baseapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}tindero{% endblock %}</title>

    <!-- Universal stylesheet. Includes Bulma framework, Spacing extension, slider extension, Bulma universal modifications -->
    <link rel="stylesheet" type="text/css" href="{% static 'baseapp/master-style.min.css' %}">

    <!-- animations -->
    <link rel="stylesheet" type="text/css" href="{% static 'baseapp/animate.min.css' %}">

    <!-- additional custom styles -->
    <link rel="stylesheet" type="text/css" href="{% static 'baseapp/base-style.css' %}">

    <!-- cropper -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.css" rel="stylesheet">

    <!-- page-specific styles -->
    {% block styles %}

    {% endblock %}

    <!-- page browser tab icon -->
    <link rel="icon" type="image/png" sizes="32x32" href="#">
</head>
<body>
    <!-- page-specific content -->
    {% block content %}
    {% endblock %}

    <!-- vuejs universal  -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js"></script>

    <!-- bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- page-specific scripts -->
    {% block script %}
    {% endblock %}
</body>
</html>

baseapp/templates/baseapp/products-list.html
{% extends "baseapp/base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'baseapp/products-list-style.css' %}">
{% endblock %}

{% block title %}Products List{% endblock %}

{% block content %}
<section id="business-products-list" class="hero is-fullheight has-background-custom-white is-vcentered-content">
    <div class="container is-fluid">
        <section class="box products-list-container">
            <div class="columns">
                <div class="column is-vcentered-content has-text-left">
                    <button class="button is-info is-one-third btn-dashboard">
                        <a href="/business/dashboard" class="has-text-white">Dashboard</a>
                    </button>
                </div>
                <div class="column is-vcentered-content has-text-centered">
                    <h1 class="title is-4 has-text-grey-darker">Products List</h1>
                    <h2 class="subtitle is-5 has-text-black">{{ business.branch_name }}</h2>
                </div>
                <div class="column is-vcentered-content has-text-right">
                    <span class="has-text-right">
                        <button class="button is-primary is-one-third btn-dashboard">
                            <a href="/business/add-product" class="has-text-white">Add Product</a>
                        </button>
                    </span>
                </div>
            </div>

            <div class="table-container">
                <table class="table is-striped is-hoverable">
                    <thead class="table__head">
                        <tr>
                            <th class="">ID</th>
                            <th class="">Name</th>
                            <th class="">Price</th>
                            <th class="">Description</th>
                            <th class="">Tags</th>
                            <th class="">Nopes</th>
                            <th class="">Eats</th>
                            <th class="">Yups</th>
                        </tr>
                    </thead>
                    <tbody class="table__body">
                        {% for food in foods %}
                            <tr>
                                <td class="col-id">{{ food.food_id }}</td>
                                <td class="col-name">{{ food.food_name }}</td>
                                <td class="col-price">P {{ food.food_price }}</td>
                                <td class="col-desc">{{ food.food_desc }}</td>
                                <td class="col-tag">{{ food.food_tag }}</td>
                                <td class="col-rate">{{ food.nope }}</td>
                                <td class="col-rate">{{ food.eat }}</td>
                                <td class="col-rate">{{ food.yup }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </section>

    </div>
</section>
{% endblock %}


{% block script %}
<script type="text/javascript">
    var app = new Vue({
        el: '#business-products-list',
        delimiters: ['${', '}'],
        data: {

        },
        methods: {

        },
        computed: {

        }
    });
</script>
{% endblock %}

baseapp/templates/baseapp/profile.html
{% extends 'baseapp/base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<p><a href="{% url 'baseapp:feed' %}"><button>Back</button></a></p>
<h1>Profile</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Name: {{ profile_form.first_name }}</p>
    <p>Birthday: {{ profile_form.bDay }}</p>
    <p>{{ image_form }}</p>
    <p><input type="submit" name="save_profile" value="Save" /></p>
</form>
<div class="modal" id="modalCrop">
    <div class="modal-card modal-card-signupBusiness">
        <div class="modal-card-body is-vcentered">
            <div class="columns is-multiline">
                <div class="column is-full">
                    <h1 class="title has-text-primary has-text-centered is 4-p-b-mg">Crop the photo</h1>
                    <img src="" id="image" style="max-width: 100%;">
                    <div class="field has-text-centered">
                    <button type="button" class="button is-primary is-half is-rounded is-shadowed m-t-md js-crop-and-upload">Crop and upload</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 128,
          minCropBoxHeight: 128,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        // $("#formUpload").submit();
        $("#modalCrop").modal('toggle');
      });

    });
</script>



{% endblock %}